name: Launch Uatu Ver4 From Evaluation PR

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  actions: write
  contents: read

jobs:
  launch:
    if: ${{ false }}
    runs-on: ubuntu-24.04
    steps:
      - run: echo 'The Ver4 evaluation has already been dispatched.'
